import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
    console.log('Seeding database...')

    // 1. Fulfillment Nodes
    await prisma.fulfillmentNode.upsert({
        where: { nodeId: 'NODE-BOM' },
        update: {},
        create: { nodeId: 'NODE-BOM', name: 'Mumbai Central' }
    })

    // 2. Products
    const sku104 = await prisma.product.upsert({
        where: { sku: 'SKU-104' },
        update: {},
        create: {
            sku: 'SKU-104',
            name: 'Wireless Earbuds',
            category: 'Audio',
            unitCost: 1200.0,
            sellingPrice: 2500.0
        }
    })

    // 3. Suppliers
    await prisma.supplier.upsert({
        where: { supplierId: 'SUP-001' },
        update: {},
        create: {
            supplierId: 'SUP-001',
            name: 'ABC Electronics',
            leadTimeDays: 5,
            minimumOrderQuantity: 100,
            fillRate: 0.92,
            reliabilityScore: 0.91,
            status: 'ACTIVE'
        }
    })

    // Alternative Supplier for Scenario 2
    await prisma.supplier.upsert({
        where: { supplierId: 'SUP-002' },
        update: {},
        create: {
            supplierId: 'SUP-002',
            name: 'Global Tech Supply',
            leadTimeDays: 3,
            minimumOrderQuantity: 50,
            fillRate: 0.88,
            reliabilityScore: 0.85,
            status: 'ACTIVE'
        }
    })

    // 4. Supplier Prods
    await prisma.supplierProduct.upsert({
        where: { supplierId_sku: { supplierId: 'SUP-001', sku: 'SKU-104' } },
        update: {},
        create: {
            supplierId: 'SUP-001',
            sku: 'SKU-104',
            unitCost: 1200.0
        }
    })

    await prisma.supplierProduct.upsert({
        where: { supplierId_sku: { supplierId: 'SUP-002', sku: 'SKU-104' } },
        update: {},
        create: {
            supplierId: 'SUP-002',
            sku: 'SKU-104',
            unitCost: 1250.0 // Slight premium
        }
    })

    // 5. Inventory for SKU-104 @ NODE-BOM
    await prisma.inventory.upsert({
        where: { sku_nodeId: { sku: 'SKU-104', nodeId: 'NODE-BOM' } },
        update: {
            currentQuantity: 220,
            reservedQuantity: 40,
            reorderPoint: 200,
            safetyStock: 150,
            dailyAverageDemand: 85.0
        },
        create: {
            sku: 'SKU-104',
            nodeId: 'NODE-BOM',
            currentQuantity: 220,
            reservedQuantity: 40,
            reorderPoint: 200,
            safetyStock: 150,
            dailyAverageDemand: 85.0
        }
    })

    // 6. Forecast & Demand History
    await prisma.forecast.upsert({
        where: { sku_nodeId: { sku: 'SKU-104', nodeId: 'NODE-BOM' } },
        update: {},
        create: {
            sku: 'SKU-104',
            nodeId: 'NODE-BOM',
            next3Days: 255,
            next5Days: 425,
            next7Days: 610,
            next14Days: 1250,
            confidence: 0.87
        }
    })

    await prisma.demandHistory.upsert({
        where: { sku_nodeId: { sku: 'SKU-104', nodeId: 'NODE-BOM' } },
        update: {},
        create: {
            sku: 'SKU-104',
            nodeId: 'NODE-BOM',
            previousAverageDailyDemand: 65,
            currentAverageDailyDemand: 85,
            trendPercentage: 31
        }
    })

    // 7. Confirmed incoming PO (the 300 units ETA 5 days)
    await prisma.purchaseOrder.upsert({
        where: { poId: 'PO-1234' },
        update: { status: 'CONFIRMED' },
        create: {
            poId: 'PO-1234',
            sku: 'SKU-104',
            nodeId: 'NODE-BOM',
            supplierId: 'SUP-001',
            quantity: 300,
            unitCost: 1200,
            totalCost: 360000,
            status: 'CONFIRMED',
            expectedArrivalDays: 5
        }
    })

    // 8. Budget and Storage
    await prisma.budget.upsert({
        where: { nodeId: 'NODE-BOM' },
        update: {
            availableBudget: 800000.0,
            monthlyBudget: 1200000.0,
            committedAmount: 400000.0
        },
        create: {
            nodeId: 'NODE-BOM',
            monthlyBudget: 1200000.0,
            committedAmount: 400000.0,
            availableBudget: 800000.0
        }
    })

    await prisma.storage.upsert({
        where: { nodeId: 'NODE-BOM' },
        update: {
            availableCapacityUnits: 500,
            totalCapacityUnits: 1000,
            occupiedCapacityUnits: 500
        },
        create: {
            nodeId: 'NODE-BOM',
            totalCapacityUnits: 1000,
            occupiedCapacityUnits: 500,
            availableCapacityUnits: 500
        }
    })

    // 9. Initial recommendation generated by the mock "system"
    await prisma.purchaseRecommendation.create({
        data: {
            sku: 'SKU-104',
            nodeId: 'NODE-BOM',
            recommendedQuantity: 800,
            reason: 'Automated Replenishment Recommendation'
        }
    })

    console.log('Seeding complete. Scenario 1 properties match exactly.')
}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.error(e)
        await prisma.$disconnect()
        process.exit(1)
    })
